repos:
  - repo: https://github.com/pre-commit/mirrors-clang-format
    rev: v17.0.6
    hooks:
      - id: clang-format
        types_or: [c++]
  - repo: local
    hooks:
      - id: clang-tidy
        name: clang-tidy
        entry: clang-tidy-19 -p build/dev --warnings-as-errors=*
        language: system
        types_or: [c++]
        files: ^(include|src)/
